In [3]:
import numpy as np


In [2]:
x=[1,2,3,4]
type(x)

list

In [3]:
y=np.array(x)

In [4]:
type(x)

list

type(y)

In [7]:
y

array([1, 2, 3, 4])

In [ ]:
# how to create user difine array ?

In [14]:
a=[]
size=int(input("size of array :"))
for i in range(size):
    value=int(input("add item :"))
    a.append(value)
c=np.array(a)
c

size of array : 4
add item : 2
add item : 2
add item : 54
add item : 54


array([ 2,  2, 54, 54])

In [17]:
# how can  we check size and shape of an array ?


In [19]:
a=np.array([25,'rahul',12,85])
a

array(['25', 'rahul', '12', '85'], dtype='<U11')

In [20]:
a.shape

(4,)

In [21]:
print("total elemets of a: ",a.size)

total elemets of a:  4


In [22]:
a.size

4

In [25]:
a=[[1,2,3],[5,4,8],[5,98,9]]
b=np.array(a)
b

array([[ 1,  2,  3],
       [ 5,  4,  8],
       [ 5, 98,  9]])

In [26]:
b.shape

(3, 3)

In [27]:
b.size

9

In [ ]:
    # iMAGES ===> pixels(0-255) ===> 0px black , 255 px white ==> Normalize(0-1)px 
    
    # Intially weights ===> 0 , 1 
    
    
    # optimization ===> 0,1 
    
    
    # matrix ===> n(rows) , n(columns) 
    
    # symmatric Matrix ===> n(rows) = n(columns) 
    
    # Aymmatric Matrix ===> n(rows) !=n(columns) 
    
    # [(1,1) , (2,2) , (3,3) , (4,4)......(n,n)]


In [ ]:
# pre difine functions 


In [ ]:
# (1). zeros() ===> It will create an array in which all the elements are 0 . 

In [30]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [34]:
b=np.zeros((4,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# (2). ones() ===> It will create an array in which all the elments are 1 . 



In [35]:
a=np.ones(2)
a

array([1., 1.])

In [36]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.shape

(3, 4)

In [39]:
a.size

12

In [ ]:
# (3). eye() ====> In this function digonalpostional elements are 1 and rest all are zero . 

In [40]:
# symmatric Matrix
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# Aymmatric Matrix
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero . 

In [7]:
a=np.diag([1,5,7,9])
a

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [ ]:
# 5 . randint ==> This  function is used to generate a random number between a given range . 

In [ ]:
# syntax == randint(min_value , max_value , total_numbers) 

In [13]:
a=np.random.randint(1,15,5)
a

array([ 6, 14, 11,  7,  5])

In [ ]:
# 6 . rand() ==> This function is used to generate a random number between 0 to 1 . 
# syntax == rand(numberof values) 


In [16]:
a=np.random.rand(4)
a

array([0.18349249, 0.95914349, 0.40771257, 0.02265732])

In [ ]:
# 7 . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well . 

# syntax == random.randn(number of values) 

In [19]:
a=np.random.randn(5)
a

array([ 1.08580124, -0.25371678,  0.05619323,  0.04961101, -2.61150395])

In [ ]:
# Reshaping Data

In [20]:
a=np.random.randint(1,50,12)
a

array([24, 21,  4, 48, 22, 20, 19,  4, 37, 33, 23, 10])

In [ ]:
# n(rows) * n(columns) = n(total_elements) 

In [21]:
a.shape

(12,)

In [22]:
a.size

12

In [29]:
a=a.reshape(2,6)
a

array([[24, 21,  4, 48, 22, 20],
       [19,  4, 37, 33, 23, 10]])

In [30]:
a = a.reshape(6,2) 
a

array([[24, 21],
       [ 4, 48],
       [22, 20],
       [19,  4],
       [37, 33],
       [23, 10]])

In [31]:
a = a.reshape(12,1) 
a

array([[24],
       [21],
       [ 4],
       [48],
       [22],
       [20],
       [19],
       [ 4],
       [37],
       [33],
       [23],
       [10]])

In [ ]:
# principal of -1 

In [33]:
a=a.reshape(-1,4)
a

array([[24, 21,  4, 48],
       [22, 20, 19,  4],
       [37, 33, 23, 10]])

In [ ]:
#  Seed Function ()  ==> We know that randint function generates random numbers .
#  Everytime we run the program  , new set of random number is generated .
#  So , solve this problem we will use seed function . 

In [36]:
import numpy as np


In [48]:
np.random.seed(5)
a=np.random.randint(1,50,12)
a

# seed me kuch likh denge to value change nhi hogi run krane pr 
# khali rkhne me value change hoti rhegi

array([36, 15, 48, 39, 17, 10,  9, 37, 40, 28, 49, 31])

In [ ]:
# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways . 

In [54]:
import numpy as np
a=np.array([1,5,8,4,6,8,4,6,5,4])
b=a[3:6]
b[:]=0
a


array([1, 5, 8, 0, 0, 0, 4, 6, 5, 4])

In [51]:
#copy
a=np.array([1,5,6,4,8,6,2,8,5])
b=a[3:6].copy()
b[:]=1
a

array([1, 5, 6, 4, 8, 6, 2, 8, 5])

In [52]:
b

array([1, 1, 1])

In [ ]:
# conditional selection 


In [57]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [59]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [60]:
a==11

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [61]:
b=[a>10]
b

[array([False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True])]

In [64]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [67]:
b=a%2==0
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

In [68]:
# or 
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [71]:
# Operations on Array 
a=np.arange(1,10)
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
a**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
a=np.array([1,5,6,8,4,5,6,5]).reshape(2,4)
a

array([[1, 5, 6, 8],
       [4, 5, 6, 5]])

In [75]:
b=np.array([5,8,4,5,8,4,5,7]).reshape(2,4)
b

array([[5, 8, 4, 5],
       [8, 4, 5, 7]])

In [76]:
a+b

array([[ 6, 13, 10, 13],
       [12,  9, 11, 12]])

In [77]:
b-a

array([[ 4,  3, -2, -3],
       [ 4, -1, -1,  2]])

In [78]:
b/a

array([[5.        , 1.6       , 0.66666667, 0.625     ],
       [2.        , 0.8       , 0.83333333, 1.4       ]])

In [79]:
a*b

array([[ 5, 40, 24, 40],
       [32, 20, 30, 35]])

In [81]:
a.dot(b)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [82]:
a.dot(b)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [ ]:
# some more important numpy functions 

In [84]:
import numpy as np
a=np.array([1,4,5,6,8,25,61,5454])
min(a)


1

In [85]:
max(a)

5454

In [86]:
#or
np.min(a)   #it will return minium value of the array 

1

In [87]:
np.max(a)

5454

In [88]:
np.argmin(a)       #it will return indexing of minimum value

0

In [89]:
np.argmax(a)    #it will return indexing of maxmim value

7

In [90]:
np.sqrt(a)

array([ 1.        ,  2.        ,  2.23606798,  2.44948974,  2.82842712,
        5.        ,  7.81024968, 73.85120175])

In [91]:
np.sin(a)

array([ 0.84147098, -0.7568025 , -0.95892427, -0.2794155 ,  0.98935825,
       -0.13235175, -0.96611777,  0.19391699])

In [ ]:
# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements . 

In [100]:
import numpy as np
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [109]:
np.random.seed(25245)
a=np.random.randint(10,25,9).reshape(3,3)
a

array([[10, 14, 23],
       [22, 15, 15],
       [19, 24, 24]])

In [110]:
sum(a)

array([51, 53, 62])

In [111]:
np.sum(a)

166

In [112]:
b=np.sum(a , axis = 1)        ###########################################################################

array([47, 52, 67])

In [117]:
np.min(a)

10

In [119]:
np.max(a)

24

In [120]:
np.cumsum(a)            ##############################################################################

array([ 10,  24,  47,  69,  84,  99, 118, 142, 166])

In [121]:
a

array([[10, 14, 23],
       [22, 15, 15],
       [19, 24, 24]])

In [ ]:
# np.unique(arr , return_index = True , return_counts = True) 

returns 3 array . 
1 . the array with unique values . 
2 . the array with respective index value . 
3 . the array with counting of frequencey . 

In [126]:
a=np.array([2,5,9,5,8,4,9,2,5])
np.unique(a ,return_index = True, return_counts = True)

(array([2, 4, 5, 8, 9]),
 array([0, 5, 1, 4, 2], dtype=int64),
 array([2, 1, 3, 1, 2], dtype=int64))

In [ ]:
# horizontal and vertical stacking

In [129]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])


In [130]:
a

array([1, 2, 3, 4])

In [131]:
b

array([5, 6, 7, 8])

In [133]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Q.1 = Write statement to import numpy ? 

#Q.2 = Create an array using numpy ? 

#Q.3 = Create an array of 10 random integers ?

 #Q.4 = Create an array of elements from  10-20? 

#Q.5 = Create an array which contains value 5 , 10 times ? 

#Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

#Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

#Q.8 = Concatenate 2D array horizontally and vertically ? 

In [135]:
# ans- 1
import numpy as np

In [146]:
# (2) ans
a=[1,4,5,8]
b=np.array(a)
print("1d aarray :",b)
c=np.array([[1,2,3],[5,6,8]])
print("2d array :\n"  ,     c)

1d aarray : [1 4 5 8]
2d array :
 [[1 2 3]
 [5 6 8]]


In [147]:
# ans - 3
a=np.random.randint(1,20,10)
a

array([ 5, 15,  4, 10, 17, 18, 16, 18, 13, 17])

In [150]:
# ans -4
a=np.arange(10,21)
print("value 10 se 20 tak :" ,a)

value 10 se 20 tak : [10 11 12 13 14 15 16 17 18 19 20]


In [154]:
# ans - 5
a=np.full(10,5)
a
# Creating an array with the value 5 repeated 10 times

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [155]:
# ans -6
a=np.array([2,5,9,4,4,96,1,5,2])
a

array([ 2,  5,  9,  4,  4, 96,  1,  5,  2])

In [158]:
a.size


9

In [159]:
a.ndim

1

In [160]:
b=np.array(a).reshape(3,3)
b


array([[ 2,  5,  9],
       [ 4,  4, 96],
       [ 1,  5,  2]])

In [163]:
# ans-7

a=np.linspace(0,1,9).reshape(3,3)
a

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [169]:
# or import
#  . rand() ==> This function is used to generate a random number between 0 to 1 . 
# syntax == rand(numberof values) 
a=np.random.rand(9).reshape(3,3)
a

array([[0.76469429, 0.25816265, 0.69552842],
       [0.81482848, 0.15097625, 0.95680766],
       [0.04876062, 0.48426946, 0.28697038]])

In [170]:
# ans - 8
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a
b

array([5, 6, 7, 8])

In [171]:
a

array([1, 2, 3, 4])

In [174]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [175]:
np.vstack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [176]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:\n", array1)
print("Array 2:\n", array2)

# Horizontal concatenation
horizontal_concat = np.concatenate((array1, array2), axis=1)
print("Horizontally concatenated array:\n", horizontal_concat)

# Horizontal stacking
horizontal_stack = np.hstack((array1, array2))
print("Horizontally stacked array:\n", horizontal_stack)

# Vertical concatenation
vertical_concat = np.concatenate((array1, array2), axis=0)
print("Vertically concatenated array:\n", vertical_concat)

# Vertical stacking
vertical_stack = np.vstack((array1, array2))
print("Vertically stacked array:\n", vertical_stack)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Horizontally concatenated array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Horizontally stacked array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically concatenated array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
